BaseUrl: "https://cwangtf.github.io/"
LanguageCode: "zh-cn"
Title: "test"

Params:
  Author: "wangtf"
  DateForm: "Jun, Jan 2, 2018"
  GoogleAnalyticsUserID: "UA-121672539-1"
  Github: "cwangtf"
  ShowRelatedPost: True
  Disqus: "unresolved"
  SyntaxHighlightTheme: "github.min.css"

Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:slug/

MetadataFormat: "yaml"